### ISSUE TITLE
Script changes are not able to start, because port 8080 is already in use 

### ISSUE THREAD

**Issue by nilssolanki** [connyay/openshift-node4#1]
After setting up a cartridge, I cloned the repository onto my computer and made some changes to `app.js`. After committing the changes via git, it still showed me the original app.js contents in the browser. So I looked at the `node-four/logs/node.log` file and saw the following:

```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventEmitter.listen (/var/lib/openshift/560ff22389f5cfca0c000136/app-root/runtime/repo/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/var/lib/openshift/560ff22389f5cfca0c000136/app-root/runtime/repo/app.js:21:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
error: Forever detected script exited with code: 1
```

Then I did an `lsof` and saw that there was another node process running, which I stopped. Yet I was still not able to restart the `app.js`. I always got the same message as above in the log, no matter if I tried to restart the application via openshift or directly via `node app.js`.

Do you have any idea which process might still be blocking port `8080` and how I could kill it?

Thank you very much in advance

**Comment by LorenzBischof** [comment]
How are you starting the server? The environment variables are different than in the standard nodejs cartridge.

**Comment by nilssolanki** [comment]
Maybe I don't understand the openshift platform enough yet. I never started it explicitly, I just counted on 
step 4 in the readme:
- Runs npm start if package.json is found in repo directory (log is written to $OPENSHIFT_NODE4_LOG_DIR)

In my `package.json`, I have the standard:

```
"scripts": {
    "start": "forever app.js"
},
```

I tried to stop all other forever processes with `forever stopall`, yet this just returned that there are no running forever processes.

I'm not quite sure what I am missing?

**Comment by connyay** [comment]
See the [example](https://github.com/connyay/openshift-node4/blob/master/template/app.js#L4-L5)

**Comment by LorenzBischof** [comment]
This also works:

```
var server_port = process.env.OPENSHIFT_NODE4_PORT || 8080
var server_ip_address = process.env.OPENSHIFT_NODE4_IP || '127.0.0.1'

var server = app.listen(server_port, server_ip_address,  function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Example app listening at http://%s:%s', host, port);
});
```

add something like "node server.js" in your package.json

**Comment by nilssolanki** [comment]
Thank you both for getting back to me: Those are in my code:

```
'use strict';
let express = require('express');
let nunjucks = require('nunjucks');

let env = process.env;
let port = env.OPENSHIFT_NODE4_PORT || process.env.PORT || 1337;
let ip = env.OPENSHIFT_NODE4_IP || '127.0.0.1';

var app = express();

nunjucks.configure('templates', {
    autoescape: true,
    express: app,
    watch: true
});

app.get('/', function(req, res) {
    res.render('index.html');
});

var listener = app.listen(port, function(){
    console.log('Listening on port ' + listener.address().port);
});
```

**Comment by connyay** [comment]
odd. Can you ssh into the box... run:
1. `gear stop`
2. `killall -9 node`
3. `gear start`

**Comment by nilssolanki** [comment]
Seems like there are no more node processes running. Could there be any other process running on that port?

```
[*.rhcloud.com asdfkjlsadjfksjadf]\> killall -9 node
node: Kein Prozess abgebrochen
```

Which is German for "no process killed".

I have previously tried to recreate the whole gear, but it didn't seem to fix the problem.

**Comment by connyay** [comment]
Ah - I didn't look closely enough at your code.

``` js
var listener = app.listen(port, function(){
    console.log('Listening on port ' + listener.address().port);
});
```

should be 

``` js
var listener = app.listen(port, ip, function(){
    console.log('Listening on port ' + listener.address().port);
});
```

**Comment by nilssolanki** [comment]
Oh wow, I can't believe I missed this... Thank you!
It works now!
