### ISSUE TITLE
hot_deploy

### ISSUE THREAD

**Issue by LorenzBischof** [connyay/openshift-node4#2]
Thanks for making this cartridge! I tried adding the hot_deploy marker, but it doesn't reload the node server. Maybe you could add this functionality?

**Comment by connyay** [comment]
That is the point of the hot_deploy...? hot_deploy says upload the new code, but don't start/stop/restart the server.

If you are looking for zero downtime deployments I would suggest scaling your cartridges to at least 2 gears. There is still some lingering problems with this method, but has worked for the most part for me

**Comment by LorenzBischof** [comment]
Ok I thought hot_deploy was for zero downtime deployment. What's the point of it if it doesn't restart the server?

**Comment by connyay** [comment]
It works for some languages / applications, but I don't think it works very well with node.

IIRC you could combine hot_deploy with pm2 instead of forever.

I went down that path awhile ago, and it ended up just being easier using multiple gears.

**Comment by nilssolanki** [comment]
Seems like there are no more node processes running. Could there be any other process running on that port?

    [*.rhcloud.com asdfkjlsadjfksjadf]\> killall -9 node
    node: Kein Prozess abgebrochen

Which is German for "no process killed".
